org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.vfs.watch=true
org.gradle.unsafe.configuration-cache-problems=warn
android.useAndroidX=true
android.enableJetifier=true
android.experimental.enableNewApkInstaller=false
kotlin.code.style=official
android.nonTransitiveRClass=true